version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: spring_test
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    expose:
      - "5432"

# wsl docker-compose up -d
# wsl docker rm my-postgres-container
# wsl docker run --name my-postgres-container -e POSTGRES_PASSWORD=mypassword -p 127.0.0.1:5432:5432 postgres
# wsl docker exec -it my-postgres-container psql -U myuser spring_test