spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring_test
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
  #    show-sql: true
  flyway:
    schemas:
      - public
  kafka:
    bootstrap-servers: localhost:29092
    listener:
      # Commit the offset after each record is processed by the listener.
      ack-mode: record
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    # URL for services registration
    service-url:
      defaultZone: http://localhost:8761/eureka
  # To generate unique ID for each instance of client
  instance:
    instance-id: ${spring.application.name}:${random.uuid}